### ISSUE TITLE
Can't complete captcha verification on local mode

### ISSUE THREAD

**Issue by neslinesli93** [drallieiv/KinanCity#81]
Hi, I'm trying the new branch `feature/captchaServer` but I'm getting an issue when visiting `http://localhost:8888/` for manual captcha solving.
I've followed the instructions reported in the releases page, thus:
- `java -jar KinanCity-captcha-server-1.3.3-SNAPSHOT.jar`
- `java -jar KinanCity-core-1.3.3-SNAPSHOT.jar` with all the other params

However, it gives me the following [error](https://i.imgur.com/nrcaMfG.png).
Thanks for any help!

**Comment by drallieiv** [comment]
Should be fixed by last release

https://github.com/drallieiv/KinanCity/releases/tag/v1.4.0-rc03-alpha

**Comment by neslinesli93** [comment]
thanks, now trying this release and it keeps giving me the error "failed to submit captcha token". any clue?

**Comment by neslinesli93** [comment]
just tried with ngrok, still failing even if it does not ask anymore to load unsafe scripts

**Comment by neslinesli93** [comment]
[this line here](https://github.com/drallieiv/KinanCity/blob/feature/captchaServer/KinanCity-captcha-server/src/main/resources/META-INF/resources/inject.js#L78) has a problem: the request to `/captcha/solve` returns a 200 after a successful response, however it doesn't contain `"ok"` so the text displays `Failed to submit captcha token.`.

My java knowledge is limited, so I really don't know if it's supposed to behave like this or not

**Comment by drallieiv** [comment]
What text ? can u come to discord ?

**Comment by drallieiv** [comment]
v1.4.0-rc03-alpha rebuilding, should be fixed.
It was working but the js displayed error anyway

**Comment by neslinesli93** [comment]
Yep, I'm on discord with the same nickname, and I've been trying to start a conversation on this issue for a couple days now.
I see you fixed the js bug, but the problem is I some other core class. Because what the js says is not that important actually, because the KinanCity core always fails with the message "Invalid captcha"

**Comment by neslinesli93** [comment]
the issue has been completely solved on branch `feature/captchaServer`, but for some reason, today I pulled from master and it stopped working again.
it says there is something wrong with the config file

**Comment by drallieiv** [comment]
Can you elaborate ?

What did you do ?
What did you expect  ?
What happened ?

**Comment by drallieiv** [comment]
no response = closed
